// General Job Fetching
export const ALL_JOBS_REQUEST = 'ALL_JOBS_REQUEST';
export const ALL_JOBS_SUCCESS = 'ALL_JOBS_SUCCESS';
export const ALL_JOBS_FAIL = 'ALL_JOBS_FAIL';

export const JOB_DETAILS_REQUEST = 'JOB_DETAILS_REQUEST';
export const JOB_DETAILS_SUCCESS = 'JOB_DETAILS_SUCCESS';
export const JOB_DETAILS_FAIL = 'JOB_DETAILS_FAIL';

// School/Employer Specific Jobs
export const MY_JOBS_REQUEST = 'MY_JOBS_REQUEST';
export const MY_JOBS_SUCCESS = 'MY_JOBS_SUCCESS';
export const MY_JOBS_FAIL = 'MY_JOBS_FAIL';

// Create New Job
export const CREATE_JOB_REQUEST = 'CREATE_JOB_REQUEST';
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS';
export const CREATE_JOB_FAIL = 'CREATE_JOB_FAIL';
export const CREATE_JOB_RESET = 'CREATE_JOB_RESET';

// Update & Delete (Admin/School)
export const UPDATE_JOB_REQUEST = 'UPDATE_JOB_REQUEST';
export const UPDATE_JOB_SUCCESS = 'UPDATE_JOB_SUCCESS';
export const UPDATE_JOB_FAIL = 'UPDATE_JOB_FAIL';
export const UPDATE_JOB_RESET = 'UPDATE_JOB_RESET';

export const DELETE_JOB_REQUEST = 'DELETE_JOB_REQUEST';
export const DELETE_JOB_SUCCESS = 'DELETE_JOB_SUCCESS';
export const DELETE_JOB_FAIL = 'DELETE_JOB_FAIL';
export const DELETE_JOB_RESET = 'DELETE_JOB_RESET';


// Candidate Actions
export const APPLY_JOB_REQUEST = 'APPLY_JOB_REQUEST';
export const APPLY_JOB_SUCCESS = 'APPLY_JOB_SUCCESS';
export const APPLY_JOB_FAIL = 'APPLY_JOB_FAIL';
export const APPLY_JOB_RESET = 'APPLY_JOB_RESET';

export const MY_APPLICATIONS_REQUEST = 'MY_APPLICATIONS_REQUEST';
export const MY_APPLICATIONS_SUCCESS = 'MY_APPLICATIONS_SUCCESS';
export const MY_APPLICATIONS_FAIL = 'MY_APPLICATIONS_FAIL';

// School Actions (Managing Applicants)
export const JOB_APPLICATIONS_REQUEST = 'JOB_APPLICATIONS_REQUEST';
export const JOB_APPLICATIONS_SUCCESS = 'JOB_APPLICATIONS_SUCCESS';
export const JOB_APPLICATIONS_FAIL = 'JOB_APPLICATIONS_FAIL';

export const UPDATE_STATUS_REQUEST = 'UPDATE_STATUS_REQUEST';
export const UPDATE_STATUS_SUCCESS = 'UPDATE_STATUS_SUCCESS';
export const UPDATE_STATUS_FAIL = 'UPDATE_STATUS_FAIL';
export const UPDATE_STATUS_RESET = 'UPDATE_STATUS_RESET';

// Exporting Data
export const EXPORT_APPLICATIONS_REQUEST = 'EXPORT_APPLICATIONS_REQUEST';
export const EXPORT_APPLICATIONS_SUCCESS = 'EXPORT_APPLICATIONS_SUCCESS';
export const EXPORT_APPLICATIONS_FAIL = 'EXPORT_APPLICATIONS_FAIL';

export const JOB_STATS_REQUEST = 'JOB_STATS_REQUEST';
export const JOB_STATS_SUCCESS = 'JOB_STATS_SUCCESS';
export const JOB_STATS_FAIL = 'JOB_STATS_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';