// GET ALL PAYMENTS
export const GET_ALL_PAYMENTS_REQUEST = 'GET_ALL_PAYMENTS_REQUEST';
export const GET_ALL_PAYMENTS_SUCCESS = 'GET_ALL_PAYMENTS_SUCCESS';
export const GET_ALL_PAYMENTS_FAIL = 'GET_ALL_PAYMENTS_FAIL';

// GET SINGLE PAYMENT
export const GET_PAYMENT_REQUEST = 'GET_PAYMENT_REQUEST';
export const GET_PAYMENT_SUCCESS = 'GET_PAYMENT_SUCCESS';
export const GET_PAYMENT_FAIL = 'GET_PAYMENT_FAIL';

// SUBMIT PAYMENT
export const SUBMIT_PAYMENT_REQUEST = 'SUBMIT_PAYMENT_REQUEST';
export const SUBMIT_PAYMENT_SUCCESS = 'SUBMIT_PAYMENT_SUCCESS';
export const SUBMIT_PAYMENT_FAIL = 'SUBMIT_PAYMENT_FAIL';
export const SUBMIT_PAYMENT_RESET = 'SUBMIT_PAYMENT_RESET';

// APPROVE PAYMENT (Admin)
export const APPROVE_PAYMENT_REQUEST = 'APPROVE_PAYMENT_REQUEST';
export const APPROVE_PAYMENT_SUCCESS = 'APPROVE_PAYMENT_SUCCESS';
export const APPROVE_PAYMENT_FAIL = 'APPROVE_PAYMENT_FAIL';
export const APPROVE_PAYMENT_RESET = 'APPROVE_PAYMENT_RESET';

// DENY PAYMENT (Admin)
export const DENY_PAYMENT_REQUEST = 'DENY_PAYMENT_REQUEST';
export const DENY_PAYMENT_SUCCESS = 'DENY_PAYMENT_SUCCESS';
export const DENY_PAYMENT_FAIL = 'DENY_PAYMENT_FAIL';
export const DENY_PAYMENT_RESET = 'DENY_PAYMENT_RESET';

// GET PAYMENT STATS (Admin)
export const GET_PAYMENT_STATS_REQUEST = 'GET_PAYMENT_STATS_REQUEST';
export const GET_PAYMENT_STATS_SUCCESS = 'GET_PAYMENT_STATS_SUCCESS';
export const GET_PAYMENT_STATS_FAIL = 'GET_PAYMENT_STATS_FAIL';

// CLEAR ERRORS
export const CLEAR_PAYMENT_ERRORS = 'CLEAR_PAYMENT_ERRORS';