// constants/planConstants.js

export const GET_ALL_PLANS_REQUEST = 'GET_ALL_PLANS_REQUEST';
export const GET_ALL_PLANS_SUCCESS = 'GET_ALL_PLANS_SUCCESS';
export const GET_ALL_PLANS_FAIL = 'GET_ALL_PLANS_FAIL';

export const GET_PLAN_REQUEST = 'GET_PLAN_REQUEST';
export const GET_PLAN_SUCCESS = 'GET_PLAN_SUCCESS';
export const GET_PLAN_FAIL = 'GET_PLAN_FAIL';

export const CREATE_PLAN_REQUEST = 'CREATE_PLAN_REQUEST';
export const CREATE_PLAN_SUCCESS = 'CREATE_PLAN_SUCCESS';
export const CREATE_PLAN_FAIL = 'CREATE_PLAN_FAIL';
export const CREATE_PLAN_RESET = 'CREATE_PLAN_RESET';

export const UPDATE_PLAN_REQUEST = 'UPDATE_PLAN_REQUEST';
export const UPDATE_PLAN_SUCCESS = 'UPDATE_PLAN_SUCCESS';
export const UPDATE_PLAN_FAIL = 'UPDATE_PLAN_FAIL';
export const UPDATE_PLAN_RESET = 'UPDATE_PLAN_RESET';

export const DELETE_PLAN_REQUEST = 'DELETE_PLAN_REQUEST';
export const DELETE_PLAN_SUCCESS = 'DELETE_PLAN_SUCCESS';
export const DELETE_PLAN_FAIL = 'DELETE_PLAN_FAIL';
export const DELETE_PLAN_RESET = 'DELETE_PLAN_RESET';

export const TOGGLE_PLAN_ACTIVE_REQUEST = 'TOGGLE_PLAN_ACTIVE_REQUEST';
export const TOGGLE_PLAN_ACTIVE_SUCCESS = 'TOGGLE_PLAN_ACTIVE_SUCCESS';
export const TOGGLE_PLAN_ACTIVE_FAIL = 'TOGGLE_PLAN_ACTIVE_FAIL';

export const SET_POPULAR_PLAN_REQUEST = 'SET_POPULAR_PLAN_REQUEST';
export const SET_POPULAR_PLAN_SUCCESS = 'SET_POPULAR_PLAN_SUCCESS';
export const SET_POPULAR_PLAN_FAIL = 'SET_POPULAR_PLAN_FAIL';

export const CLEAR_PLAN_ERRORS = 'CLEAR_PLAN_ERRORS';