// GET MY SUBSCRIPTION
export const GET_MY_SUBSCRIPTION_REQUEST = 'GET_MY_SUBSCRIPTION_REQUEST';
export const GET_MY_SUBSCRIPTION_SUCCESS = 'GET_MY_SUBSCRIPTION_SUCCESS';
export const GET_MY_SUBSCRIPTION_FAIL = 'GET_MY_SUBSCRIPTION_FAIL';

// CHECK CAN POST JOB
export const CHECK_CAN_POST_JOB_REQUEST = 'CHECK_CAN_POST_JOB_REQUEST';
export const CHECK_CAN_POST_JOB_SUCCESS = 'CHECK_CAN_POST_JOB_SUCCESS';
export const CHECK_CAN_POST_JOB_FAIL = 'CHECK_CAN_POST_JOB_FAIL';

// INCREMENT JOB POST
export const INCREMENT_JOB_POST_REQUEST = 'INCREMENT_JOB_POST_REQUEST';
export const INCREMENT_JOB_POST_SUCCESS = 'INCREMENT_JOB_POST_SUCCESS';
export const INCREMENT_JOB_POST_FAIL = 'INCREMENT_JOB_POST_FAIL';
export const INCREMENT_JOB_POST_RESET = 'INCREMENT_JOB_POST_RESET';

// DECREASE CV COUNT (CV Download)
export const DECREASE_CV_COUNT_REQUEST = 'DECREASE_CV_COUNT_REQUEST';
export const DECREASE_CV_COUNT_SUCCESS = 'DECREASE_CV_COUNT_SUCCESS';
export const DECREASE_CV_COUNT_FAIL = 'DECREASE_CV_COUNT_FAIL';
export const DECREASE_CV_COUNT_RESET = 'DECREASE_CV_COUNT_RESET';

// CLEAR ERRORS
export const CLEAR_SUBSCRIPTION_ERRORS = 'CLEAR_SUBSCRIPTION_ERRORS';